CREATE DATABASE IF NOT EXISTS FOOTBALL;
CREATE SCHEMA IF NOT EXISTS FOOTBALL.RAW;
CREATE SCHEMA IF NOT EXISTS FOOTBALL.ANALYTICS;

CREATE OR REPLACE TABLE FOOTBALL.RAW.PLAYERS_JSON (ingest_ts TIMESTAMP_NTZ, league NUMBER, payload VARIANT);
CREATE OR REPLACE TABLE FOOTBALL.RAW.TOPSCORERS_JSON (ingest_ts TIMESTAMP_NTZ, league NUMBER, payload VARIANT);
CREATE OR REPLACE TABLE FOOTBALL.RAW.TOPASSISTS_JSON (ingest_ts TIMESTAMP_NTZ, league NUMBER, payload VARIANT);

CREATE OR REPLACE TABLE FOOTBALL.ANALYTICS.REF_COMPETITIONS (
  comp_id NUMBER,
  name STRING,
  weight NUMBER(3,1)
);

INSERT OVERWRITE INTO FOOTBALL.ANALYTICS.REF_COMPETITIONS VALUES
  (2,'UEFA Champions League',3.0),
  (39,'Premier League',2.0),
  (140,'LaLiga',2.0),
  (61,'Ligue 1',2.0),
  (78,'Bundesliga',2.0),
  (135,'Serie A',2.0);
